export const departobj = [
  {
    id: "#it",
    title: `Information Technology`,
    img: "/DepartmentAssets/it.webp",
    des: "test",
    color: "#37c0ff",
    bgtext: "Tech",
  },
  {
    id: "#mech",
    title: "Mechanical Engineering",
    img: "/DepartmentAssets/mech.webp",
    des: "test",
    color: "#67ff45",
    bgtext: "Mech",
  },
  {
    id: "#civil",
    title: "Civil Engineering ",
    img: "/DepartmentAssets/civil.webp",
    des: "test",
    color: "#ff3b41",
    bgtext: "Civil",
  },
  {
    id: "#eee",
    title: "Electrical\t& Electronics\tEngineering  ",
    img: "/DepartmentAssets/eee.webp",
    des: "test",
    color: "#ff6d41",
    bgtext: "Elect",
    mbtm: "-30px",
  },
  {
    id: "#aids",
    title: "Artificial Intelligence",
    img: "/DepartmentAssets/ai.webp",
    des: "test",
    color: "#ff58c2",
    bgtext: "Artif",
  },
  {
    id: "#chem",
    title: "Chemical Engineering",
    img: "/DepartmentAssets/chem.webp",
    des: "test",
    color: "#ff6d41",
    bgtext: "Chem",
  },
  {
    id: "#agri",
    title: "Agricultural Engineering",
    img: "/DepartmentAssets/agri.webp",
    des: "test",
    color: "#37c0ff",
    bgtext: "Agri",
  },
  {
    id: "#cse",
    title: "Computer\tScience &\tEngineering",
    img: "/DepartmentAssets/cse.webp",
    des: "test",
    color: "#67ff45",
    bgtext: "Compu",
  },

  {
    id: "#ece",
    title: "Electronics\t& Communication\tEngineering",
    img: "/DepartmentAssets/ece.webp",
    des: "test",
    color: "#37c0ff",
    bgtext: "Elect",
    mbtm: "-30px",
  },
  {
    id: "#eie",
    title: "Electronics\t& Instrumentation\tEngineering",
    img: "/DepartmentAssets/eie.webp",
    des: "test",
    color: "#ff3b41",
    bgtext: "iInst",
    mbtm: "-30px",
  },
  {
    id: "#bme",
    title: "Bio\tMedical Engineering",
    img: "/DepartmentAssets/bme.webp",
    des: "test",
    color: "#ff58c2",
    bgtext: "BioMed",
  },
  {
    id: "#med",
    title: "Medical Electronics",
    img: "/DepartmentAssets/med.webp",
    des: "test",
    color: "#ff6d41",
    bgtext: "Medi",
  },
  {
    id: "#mba",
    title: "Master\tof\tBusiness Administration",
    img: "/DepartmentAssets/mba.webp",
    des: "test",
    color: "#67ff45",
    bgtext: "Busin",
  },
];

export const comobj = [
  {
    id: "#paper",
    title: "Paper Presentation",
    img: "/DepartmentAssets/paper.webp",
    des: "test",
    color: "#37c0ff",
    bgtext: "Paper",
  },

  {
    id: "#project",
    title: "Project Display",
    img: "/DepartmentAssets/proj.webp",
    des: "test",
    color: "#ff3b41",
    bgtext: "Proj",
  },
];
