export const EventDetails = [
  {
    title: "Information Technology",
    eventslist: [
      {
        name: "Switcheroo",
        desc: "Switcheroo is a coding challenge with a twist.",
        date: "10 Nov 2022",
        rulesAndReg:"A fun event spanning over two rounds. Maximum participation 2 person per team. In the case of cheating, using of phone or using of any unnecessary gadgets will make the team disqualify. Shortlisted participants of Round-1 will appear for Round-2 for which above rules are applicable",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 2",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "10 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 3",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "11 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 4",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "11 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Workshop 1",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        tag: "WORKSHOP",
        date: "10 Nov 2022",
        img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
      },
      {
        name: "Workshop 2",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        tag: "WORKSHOP",
        date: "11 Nov 2022",
        img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
      },
    ],
  },
  {
    title: "Computer Science & Engineering",
    eventslist: [
      {
        name: "Event 1 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "10 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 2 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "10 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 3 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "11 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Event 4 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        date: "11 Nov 2022",
        tag: "EVENT",
        img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
      },
      {
        name: "Workshop 1 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        tag: "WORKSHOP",
        date: "10 Nov 2022",
        img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
      },
      {
        name: "Workshop 2 test",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
        tag: "WORKSHOP",
        date: "11 Nov 2022",
        img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
      },
    ],
  },
];

// {
//   title: "Information Technology",
//   name: "Event 1",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   date: "10 Nov 2022",
//   tag: "EVENT",
//   img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
// },
// {
//   // title: "Information Technology",
//   name: "Event 2",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   date: "10 Nov 2022",
//   tag: "EVENT",
//   img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
// },
// {
//   // title: "Information Technology",
//   name: "Event 3",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   date: "11 Nov 2022",
//   tag: "EVENT",
//   img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
// },
// {
//   // title: "Information Technology",
//   name: "Event 4",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   date: "11 Nov 2022",
//   tag: "EVENT",
//   img: "https://www.gstatic.com/mobilesdk/191021_mobilesdk/discoverycards/appdistro@2x.png",
// },
// {
//   // title: "Information Technology",
//   name: "Workshop 1",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   tag: "WORKSHOP",
//   date: "10 Nov 2022",
//   img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
// },
// {
//   // title: "Information Technology",
//   name: "Workshop 2",
//   desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, totam?",
//   tag: "WORKSHOP",
//   date: "11 Nov 2022",
//   img: "https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg",
// },
// ];
